# Generated by Django 4.0.2 on 2022-02-12 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kusuriapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='ユーザーID')),
                ('login_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='ログイン')),
                ('create_data', models.DateField(auto_now_add=True)),
                ('update_data', models.DateField(auto_now=True)),
                ('delete_data', models.DateField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', kusuriapp.models.UserModel()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineMangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_dossage', models.IntegerField(blank=True, default=0, null=True, verbose_name='服用量')),
                ('taking_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='服用単位')),
                ('taking_start', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 18, 54, 43, 617503), null=True, verbose_name='服用開始')),
                ('taking_end', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 18, 54, 43, 617515), null=True, verbose_name='服用終了')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='薬メモ')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineNameManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='服用者')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='TakingTimeAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_time', models.TimeField(default=None, verbose_name='服用時刻')),
            ],
        ),
        migrations.CreateModel(
            name='TakingDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_dosage', models.IntegerField(blank=True, default=0, null=True, verbose_name='服用量')),
                ('taking_unit', models.IntegerField(blank=True, default=0, null=True, verbose_name='服用単位')),
                ('taking_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='服用回数')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicinemangement', verbose_name='服用薬')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicinenamemanagement', verbose_name='服用者')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='服用薬')),
                ('kinds', models.CharField(blank=True, choices=[('0', '処方'), ('1', '処方（ジェネリック）'), ('2', '処方（漢方）'), ('3', '市販薬'), ('4', '市販薬（子供用）'), ('5', 'セルフメディケーション税剤対象')], default='', max_length=50, null=True, verbose_name='種別')),
                ('dosage_form', models.CharField(blank=True, choices=[('0', '散剤'), ('1', '錠剤'), ('2', 'カプセル'), ('3', '液剤'), ('4', '外用薬'), ('5', '注射剤'), ('6', '自己注射剤'), ('7', 'その他')], default='', max_length=50, null=True, verbose_name='剤型')),
                ('socienty', models.CharField(blank=True, choices=[('0', '日医工株式会社'), ('1', '沢井製薬株式会社'), ('2', '東和薬品株式会社'), ('3', '日本ジェネリック株式会社'), ('4', 'ファイザー株式会社'), ('6', 'ニプロ株式会社（528）'), ('7', '武田テバファーマ株式会社'), ('8', '株式会社陽進堂'), ('9', '共和薬品工業株式会社'), ('10', 'Meiji Seika ファルマ株式会社'), ('11', '高田製薬株式会社'), ('12', '辰巳化学株式会社'), ('13', '第一三共株式会社'), ('14', 'サンド株式会社'), ('15', '日本ケミファ株式会社'), ('16', 'キョーリンリメディオ株式会社'), ('17', '日新製薬株式会社'), ('18', '鶴原製薬株式会社'), ('19', '田辺三菱製薬株式会社'), ('20', '小林化工株式会社'), ('21', '共創未来ファーマ株式会社'), ('22', '第一三共エスファ株式会社'), ('23', '株式会社ツムラ'), ('24', '富士製薬工業株式会社'), ('25', '日本薬品工業株式会社'), ('26', 'アルフレッサファーマ株式会社'), ('27', '株式会社三和化学研究所'), ('28', '大原薬品工業株式会社'), ('29', '大塚製薬株式会社'), ('30', '丸石製薬株式会社'), ('31', 'エーザイ株式会社'), ('32', '協和キリン株式会社'), ('33', 'ニプロESファーマ株式会社'), ('34', '科研製薬株式会社'), ('35', '塩野義製薬株式会社'), ('36', 'ノバルティスファーマ株式会社'), ('37', '持田製薬株式会社'), ('38', '大日本住友製薬株式会社'), ('39', 'アステラス製薬株式会社'), ('40', '扶桑薬品工業株式会社'), ('41', '健栄製薬株式会社'), ('42', 'あすか製薬株式会社'), ('43', 'テルモ株式会社'), ('44', '吉田製薬株式会社'), ('45', 'グラクソ・スミスクライン株式会社'), ('46', 'サノフィ株式会社'), ('47', '日本化薬株式会社'), ('48', '鳥居薬品株式会社'), ('49', '大杉製薬株式会社'), ('50', 'バイエル薬品株式会社'), ('51', '帝國製薬株式会社'), ('52', '日本新薬株式会社'), ('53', '中外製薬株式会社'), ('54', 'ヤンセン ファーマ株式会社'), ('55', 'キッセイ薬品工業株式会社'), ('56', 'サンファーマ株式会社'), ('57', '岩城製薬株式会社'), ('58', 'クラシエ薬品株式会社'), ('59', '小太郎漢方製薬株式会社'), ('60', '武田薬品工業株式会社'), ('61', '久光製薬株式会社'), ('62', '参天製薬株式会社'), ('63', '小野薬品工業株式会社'), ('64', '光製薬株式会社'), ('65', 'ダイト株式会社'), ('67', '日東メディック株式会社'), ('68', '武田テバ薬品株式会社'), ('69', '全星薬品工業株式会社'), ('70', 'ヴィアトリス製薬株式会社'), ('71', '興和株式会社'), ('72', '富士フイルム富山化学株式会社'), ('73', '帝人ファーマ株式会社'), ('74', 'マイランEPD合同会社'), ('75', '大鵬薬品工業株式会社'), ('76', '日本イーライリリー株式会社'), ('77', 'MSD株式会社'), ('78', 'コーアイセイ株式会社'), ('79', '日本臓器製薬株式会社'), ('80', 'ノボノルディスクファーマ株式会社'), ('81', '株式会社日本点眼薬研究所'), ('82', 'LTLファーマ株式会社'), ('83', 'アストラゼネカ株式会社'), ('84', '共和クリティケア株式会社'), ('85', 'わかもと製薬株式会社'), ('86', '杏林製薬株式会社'), ('87', '大正製薬株式会社'), ('88', '株式会社フェルゼンファーマ'), ('89', '旭化成ファーマ株式会社'), ('90', '本草製薬'), ('91', 'あゆみ製薬株式会社'), ('92', 'EAファーマ株式会社'), ('93', '千寿製薬株式会社'), ('94', 'トーアエイヨー株式会社'), ('95', '日本ベーリンガーインゲルハイム株式会社'), ('96', 'CSLベーリング株式会社'), ('97', '一般社団法人 日本血液製剤機構'), ('98', 'ラクール薬品販売株式会社'), ('99', 'ブリストル・マイヤーズ スクイブ株式会社'), ('100', 'ゼリア新薬工業株式会社'), ('101', 'マルホ株式会社'), ('102', 'セオリア ファーマ株式会社'), ('103', '佐藤製薬株式会社'), ('104', '太陽ファルマ株式会社'), ('105', 'テイカ製薬株式会社'), ('106', '太虎精堂製薬株式会社'), ('107', '株式会社 大塚製薬工場'), ('108', 'オルガノン株式会社'), ('109', '皇漢堂製薬株式会社'), ('110', '三和生薬株式会社'), ('111', 'シオエ製薬株式会社'), ('112', '小堺製薬'), ('113', '藤永製薬株式会社'), ('114', '株式会社ビオメディクス'), ('115', 'Me ファルマ株式会社'), ('116', '三笠製薬株式会社'), ('117', '藤本製薬株式会社'), ('118', 'カイゲンファーマ株式会社'), ('119', '祐徳薬品工業株式会社'), ('120', '株式会社ヤクルト本社'), ('121', '株式会社 エッセンシャルファーマ'), ('122', 'シオノケミカル株式会社'), ('123', '中北薬品株式会社'), ('124', '寿製薬株式会社'), ('125', 'アッヴィ合同会社'), ('126', '堀井薬品工業株式会社'), ('127', 'ノーベルファーマ株式会社'), ('128', 'フェリング・ファーマ株式会社'), ('129', '松浦薬業株式会社'), ('130', '昭和薬品化工株式会社'), ('131', 'ギリアド・サイエンシズ株式会社'), ('132', '岡山大鵬薬品株式会社'), ('133', '株式会社オーファンパシフィック'), ('134', '株式会社 ミノファーゲン製薬'), ('135', 'ヴィーブヘルスケア株式会社'), ('136', 'メルクバイオファーマ株式会社'), ('137', 'JCRファーマ株式会社'), ('138', 'DSファーマプロモ株式会社'), ('139', 'レコルダティ・レア・ディジーズ・ジャパン株式会社'), ('140', 'コーアバイオテックベイ株式会社'), ('141', 'ジェイドルフ製薬株式会社'), ('142', '東菱薬品工業株式会社'), ('143', 'ジョンソン・エンド・ジョンソン株式会社'), ('144', 'ムンディファーマ株式会社'), ('145', 'アムジェン株式会社'), ('146', '株式会社富士薬品'), ('147', '日本アルコン株式会社'), ('148', '日本製薬株式会社'), ('149', '富士化学工業株式会社'), ('150', 'バイオジェン・ジャパン株式会社'), ('151', '大興製薬株式会社'), ('152', '協和化学工業株式会社'), ('153', 'ビオフェルミン製薬株式会社'), ('154', '長生堂製薬株式会社'), ('155', '化研生薬株式会社'), ('156', '全薬工業株式会社'), ('157', '原沢製薬工業'), ('158', 'ユーシービージャパン株式会社'), ('159', '日本歯科薬品株式会社'), ('160', 'ゾンネボード製薬株式会社'), ('162', '天藤製薬株式会社'), ('163', '田村薬品工業株式会社'), ('164', 'サラヤ株式会社'), ('165', '株式会社ビーブランド・メディコーデンタル'), ('166', '第一薬品産業株式会社'), ('167', '東亜新薬株式会社'), ('168', 'セルトリオン・ヘルスケア・ジャパン株式会社'), ('169', 'SKIファーマ株式会社'), ('170', 'アボットジャパン合同会社'), ('171', 'シンバイオ製薬株式会社'), ('172', '森下仁丹株式会社'), ('173', 'ミヤリサン製薬株式会社'), ('174', '株式会社伏見製薬所'), ('175', '生晃栄養薬品株式会社'), ('176', 'ニチバン'), ('177', '株式会社龍角散'), ('178', '日東薬品工業株式会社'), ('179', 'サンスター'), ('180', 'アミカス・セラピューティクス株式会社'), ('181', '日本セルヴィエ株式会社'), ('182', 'インサイト・バイオサイエンシズ・ジャパン合同会社'), ('183', 'インスメッド合同会社'), ('184', '楽天メディカル株式会社'), ('185', 'ニプロファーマ株式会社'), ('186', 'エフピー株式会社'), ('187', 'マイラン製薬株式会社')], default='', max_length=50, null=True, verbose_name='メーカー')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicinenamemanagement', verbose_name='服用者')),
            ],
        ),
        migrations.AddField(
            model_name='medicinemangement',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicineregister', verbose_name='服用薬'),
        ),
        migrations.AddField(
            model_name='medicinemangement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicinenamemanagement', verbose_name='服用者'),
        ),
        migrations.AddField(
            model_name='medicinemangement',
            name='taking_time',
            field=models.ManyToManyField(to='kusuriapp.TakingTimeAlarm', verbose_name='服用時刻'),
        ),
        migrations.AddField(
            model_name='medicinemangement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
