# Generated by Django 4.0.2 on 2022-02-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemangement',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicineregister', verbose_name='服用薬'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='服用開始'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='medicine',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='服用薬'),
        ),
    ]
