# Generated by Django 4.0.2 on 2022-02-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0002_alter_medicinemangement_medicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingtimealarm',
            name='taking_time',
        ),
        migrations.AddField(
            model_name='takingtimealarm',
            name='taking_time',
            field=models.TimeField(default=None, verbose_name='服用時刻'),
        ),
    ]
