# Generated by Django 4.0.2 on 2022-02-22 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0003_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymedicinename',
            options={'verbose_name_plural': '薬及び会社リスト'},
        ),
        migrations.AlterField(
            model_name='companymedicinename',
            name='company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='会社ID'),
        ),
        migrations.AlterField(
            model_name='companymedicinename',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='companymedicinename',
            name='initials',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='頭文字'),
        ),
        migrations.AlterField(
            model_name='companymedicinename',
            name='medicine_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='薬ID'),
        ),
        migrations.AlterField(
            model_name='companymedicinename',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='薬名'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 22, 19, 3, 49, 989164), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 22, 19, 3, 49, 989154), null=True, verbose_name='服用開始'),
        ),
        migrations.AlterModelTable(
            name='companymedicinename',
            table='link',
        ),
    ]
