# Generated by Django 4.0.2 on 2022-02-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0003_remove_takingtimealarm_taking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingtimealarm',
            name='taking_time',
        ),
        migrations.AddField(
            model_name='takingtimealarm',
            name='taking_time',
            field=models.ManyToManyField(to='kusuriapp.TakingTimeAlarm', verbose_name='服用時刻'),
        ),
    ]
