# Generated by Django 4.0.2 on 2022-02-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0006_kusuridata_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 21, 38, 33, 53593), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 21, 38, 33, 53583), null=True, verbose_name='服用開始'),
        ),
        migrations.AlterModelTable(
            name='companymedicinename',
            table='kusuri_datas',
        ),
    ]
