# Generated by Django 4.0.2 on 2022-02-24 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0007_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 14, 8, 45, 640421), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 14, 8, 45, 640409), null=True, verbose_name='服用開始'),
        ),
    ]
