# Generated by Django 4.0.2 on 2022-02-26 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0008_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KusuriData',
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 14, 50, 43, 18665), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 14, 50, 43, 18652), null=True, verbose_name='服用開始'),
        ),
    ]
