# Generated by Django 4.0.2 on 2022-02-26 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0009_delete_kusuridata_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 14, 57, 50, 726270), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 14, 57, 50, 726258), null=True, verbose_name='服用開始'),
        ),
        migrations.AlterModelTable(
            name='companymedicinename',
            table=None,
        ),
    ]
