# Generated by Django 4.0.2 on 2022-03-01 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0010_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineregister',
            name='socienty',
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 21, 22, 28, 510437), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 21, 22, 28, 510425), null=True, verbose_name='服用開始'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='medicine',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.companymedicinename', verbose_name='服用薬'),
        ),
    ]
