# Generated by Django 4.0.2 on 2022-02-26 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0010_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineregister',
            name='socienty',
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 16, 17, 58, 384334), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 16, 17, 58, 384319), null=True, verbose_name='服用開始'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='medicine',
            field=models.ForeignKey(blank=True, default='', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.companymedicinename', verbose_name='服用薬'),
        ),
    ]
