# Generated by Django 4.0.2 on 2022-03-14 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0012_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_1', models.DateField(blank=True, null=True, verbose_name='サンプル項目1 日付')),
                ('sample_2', models.DateTimeField(blank=True, null=True, verbose_name='サンプル項目2 日付時刻')),
                ('sample_3', models.TimeField(blank=True, null=True, verbose_name='サンプル項目3 日時')),
                ('sample_4_start', models.DateField(blank=True, null=True, verbose_name='サンプル項目4 期間 開始日')),
                ('sample_4_end', models.DateField(blank=True, null=True, verbose_name='サンプル項目4 期間 終了日')),
            ],
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 19, 4, 8, 554721), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 19, 4, 8, 554710), null=True, verbose_name='服用開始'),
        ),
    ]
