# Generated by Django 4.0.2 on 2022-04-02 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0013_item_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineregister',
            name='name',
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 2, 13, 15, 13, 189890), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 2, 13, 15, 13, 189861), null=True, verbose_name='服用開始'),
        ),
    ]
