# Generated by Django 4.0.2 on 2022-06-11 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0016_alter_medicinemangement_taking_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingdosage',
            name='taking_dosage',
        ),
        migrations.RemoveField(
            model_name='takingdosage',
            name='taking_number',
        ),
        migrations.RemoveField(
            model_name='takingdosage',
            name='taking_unit',
        ),
        migrations.RemoveField(
            model_name='takingdosage',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='companymedicinename',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='薬名'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 13, 37, 16, 354986), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 13, 37, 16, 354972), null=True, verbose_name='服用開始'),
        ),
    ]
