# Generated by Django 4.0.2 on 2022-06-18 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kusuriapp', '0017_remove_takingdosage_taking_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 18, 13, 47, 1, 187850), null=True, verbose_name='服用終了'),
        ),
        migrations.AlterField(
            model_name='medicinemangement',
            name='taking_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 18, 13, 47, 1, 187808), null=True, verbose_name='服用開始'),
        ),
        migrations.AlterField(
            model_name='takingdosage',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusuriapp.medicineregister', verbose_name='服用薬'),
        ),
        migrations.AlterField(
            model_name='takingdosage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='服用者'),
        ),
    ]
